# fly.toml app configuration file generated for werwolf on 2023-06-07T16:32:19+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "werwolf"
primary_region = "otp"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
