providers = []
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1680566572'

[variables]
NIXPACKS_METADATA = 'rust'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'
[phases.build]
dependsOn = ['setup', 'install']
cmds = [
    'mkdir -p bin',
    'cargo build --release --target x86_64-unknown-linux-musl',
    'cp target/x86_64-unknown-linux-musl/release/werwolf bin',
    '(cd web; pnpm run build)',
]
cacheDirectories = [
    '/root/.cargo/git',
    '/root/.cargo/registry',
    'target',
    'node_modules/.cache',
]

[phases.install]
dependsOn = ['setup']
cmds = ['(cd web; pnpm i --frozen-lockfile)']
cacheDirectories = ['/root/.local/share/pnpm/store/v3']
paths = ['/app/node_modules/.bin']

[phases.setup]
nixPkgs = [
    'binutils',
    'gcc',
    '(rust-bin.stable.latest.default.override { targets = ["x86_64-unknown-linux-musl"]; })',
    'musl',
    'musl.dev',
    'nodejs-16_x',
    'pnpm-7_x',
]
nixOverlays = [
    'https://github.com/oxalica/rust-overlay/archive/master.tar.gz',
    'https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz',
]
nixpkgsArchive = '293a28df6d7ff3dec1e61e37cc4ee6e6c0fb0847'

[start]
cmd = './bin/werwolf'
runImage = 'ubuntu:jammy'
onlyIncludeFiles = ['./bin/werwolf', './web/dist']
