// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LobbySettings { available_roles: Array<string>, roles: Array<number>, admin: string | null, }