// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LobbySettings } from "./LobbySettings";
import type { Player } from "./Player";

export type ToClient = { type: "welcome", settings: LobbySettings, players: Array<string>, } | { type: "newsettings" } & LobbySettings | { type: "joined", player: Player, } | { type: "left", player: Player, } | { type: "started" } | { type: "nameaccepted", name: string, } | { type: "namerejected" } | { type: "text", text: string, } | { type: "question", id: number, text: string, options: Array<string>, } | { type: "ended" };