// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Player } from "./Player";

export type ToServer = { type: "start" } | { type: "response", id: number, choice: number, } | { type: "kick", player: Player, } | { type: "changeroles", new_roles: Array<number>, };