// Generated by ts-to-zod
import { z } from "zod";

const toClientStartedSchema = z.object({
  type: z.literal("started"),
});

const toClientNameAcceptedSchema = z.object({
  type: z.literal("name_accepted"),
  name: z.string(),
});

const toClientNameRejectedSchema = z.object({
  type: z.literal("name_rejected"),
});

const toClientTextSchema = z.object({
  type: z.literal("text"),
  text: z.string(),
});

const toClientQuestionSchema = z.object({
  type: z.literal("question"),
  id: z.number(),
  text: z.string(),
  options: z.array(z.string()),
});

const toClientEndedSchema = z.object({
  type: z.literal("ended"),
});

const toServerStartSchema = z.object({
  type: z.literal("start"),
});

const toServerResponseSchema = z.object({
  type: z.literal("response"),
  id: z.number(),
  choice: z.number(),
});

const toServerChangeRolesSchema = z.object({
  type: z.literal("change_roles"),
  new_roles: z.array(z.number()),
});

export const playerSchema = z.object({
  name: z.string(),
});

export const lobbySettingsSchema = z.object({
  available_roles: z.array(z.string()),
  roles: z.array(z.number()),
  admin: z.string().optional(),
});

const toClientWelcomeSchema = z.object({
  type: z.literal("welcome"),
  settings: lobbySettingsSchema,
  players: z.array(z.string()),
});

const toClientNewSettingsSchema = z.object({
  type: z.literal("new_settings"),
  settings: lobbySettingsSchema,
});

const toClientJoinedSchema = z.object({
  type: z.literal("joined"),
  player: playerSchema,
});

const toClientLeftSchema = z.object({
  type: z.literal("left"),
  player: playerSchema,
});

const toServerKickSchema = z.object({
  type: z.literal("kick"),
  player: playerSchema,
});

export const toClientSchema = z.union([
  toClientWelcomeSchema,
  toClientNewSettingsSchema,
  toClientJoinedSchema,
  toClientLeftSchema,
  toClientStartedSchema,
  toClientNameAcceptedSchema,
  toClientNameRejectedSchema,
  toClientTextSchema,
  toClientQuestionSchema,
  toClientEndedSchema,
]);

export const toServerSchema = z.union([
  toServerStartSchema,
  toServerResponseSchema,
  toServerKickSchema,
  toServerChangeRolesSchema,
]);
